### PR TITLE
Es 223 config

### LINKED ISSUE #223: Need config option for “Automatically connect at startup”. Drop "Local Copy".
The current 'config' module offers no configuration option to “Automatically connect at startup” or a “Hardware Interface” (None/GPIO/Serial port) option.  We should add them, and make sure the config/preferences dialog reads/writes these options.

### PR DESCRIPTION
**Pull request by AESilky**
Updated pykob.config and the Configure CLI to support the `auto_connect` property.

Also updated MKOB (in `kobmain`) to use the value to automatically connect (or not).

Closes #223

### CODE REVIEW

**Comment by AESilky** [comment]
See comments in #223 for change descriptions reasons for changes.

**Comment by AESilky** [comment]
Removed redundant configuration values from `kobconfig` and used the values from `config`. Left the GUI specific values.

**Comment by AESilky** [comment]
@pwdirks Did you put a review comment in the file? I don't see one, but maybe just missing it. Where am I missing an 'R'?
Would like to get this submitted & merged so you can use it in the config dialog.

**Comment by leskerr** [comment]
> @pwdirks Did you put a review comment in the file? I don't see one, but maybe just missing it. Where am I missing an 'R'?

There's probably a better way in GitHub for me to provide this kind of feedback, but line 71 in `kobmain.py` reads

```
if connected and emote:
```

I was waiting for this to be fixed before providing my review.

~Les

**Comment by pwdirks** [comment]
Sorry - I put the comment in but must’ve forgotten to hit “Finish review”.  Les is right - that’s the spot where the “r” was missing.

73, -Patrick.

**Comment by AESilky** [comment]
Okay. I'll fix that.

Yes, maybe just didn't submit. I'm sure you know you can click on a line in the code review and type in a comment.

**Comment by AESilky** [comment]
Updated.

**Comment by leskerr** [comment]
On trying to connect I get this error:

```
C:\Users\Les\Documents\GitHub\PyKOB>py mkob.pyw
PyKOB 1.2.14
MorseKOB 4.0.16
Tcl/Tk 8.6/8.6
2021-01-14 09:26:44 INFO:       Interface for key and/or sounder on serial port 'COM3' not available. Key and sounder will not be used.
2021-01-14 09:26:44 INFO:       Record to 'Session-20210114-0926.json'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Les\Documents\GitHub\PyKOB\kobactions.py", line 120, in doConnect
    km.toggle_connect()
  File "C:\Users\Les\Documents\GitHub\PyKOB\kobmain.py", line 151, in toggle_connect
    Internet.connect(config.wireNo)
AttributeError: module 'pykob.config' has no attribute 'wireNo'
```

Here's my current configuration:

```
C:\Users\Les\Documents\GitHub\PyKOB>py configure.py
======================================
        System Information
======================================
User: Les
User Home Path: C:\Users\Les
User Configuration File: C:\Users\Les\AppData\Local\pykob\config-les.ini
App Configuration File C:\ProgramData\pykob\config_app.ini
OS: nt
System: Windows
Version: 10
Platform: win32
PyKOB: 1.2.14
Python: 3.7.2
PyAudio: 0.2.11
PySerial: 3.4
Host: Kerr-SurfacePro
======================================
          Configuration
======================================
Serial serial_port: 'COM3'
--------------------------------------
Auto Connect to Wire: OFF
Code type: AMERICAN
Interface type: LOOP
Invert key input: OFF
Remote send: ON
KOB Server URL: mtc-kob.dyndns.org:7890
Sound: ON
Sounder: ON
Spacing: CHAR
Station: AC - Les - Seattle, WA
Wire: 105
Character speed 18
Words per min speed: 30
```

**Comment by AESilky** [comment]
@leskerr Looking at your error.

**Comment by pwdirks** [comment]
I hit the same testing my config changes for the removal of kobconfig.py.  The ‘config’ option is ‘config.wire’.  I thought I had it right in my branch?  Was this before the merge of my change?

73, -Patrick.

**Comment by AESilky** [comment]
I fixed it in my branch and pushed as-is. Now I'm going to merge your branch in to resolve the conflicts.
I tested with the CLI apps and MKOB and all work now. MKOB also auto-connects if the option is set to ON.

**Comment by AESilky** [comment]
@leskerr @pwdirks I merged the current master into this and resolved conflicts. For most I took master. There were a couple that I took mine because I changed `config.wire` to be an int value, so there is not a need to cast/convert it when it is used.

**Comment by AESilky** [comment]
Ah, but now in testing I get an error. I'll track that down and post a change.

**Comment by AESilky** [comment]
Okay, works now. For some reason (operator error) one of my merged files didn't get picked up.

**Review by leskerr — APPROVED** [review]

**Pull request merged**
