### PR TITLE
Get MKOB settings from pykob.config

### PR DESCRIPTION
**Pull request by leskerr**
This is an interim fix to the MKOB prototype, pending resolution by @AESilky and @pwdirks on how to employ a config object. These changes will eventually be superseded, so don't waste time reviewing the details of what is essentially throwaway code. Basically, what I did was temporarily repurpose my old (simplistic) `kobconfig` module to make use of the `pykob.config` module.

### CODE REVIEW

**Comment by AESilky** [comment]
Everything looks good. This will close #71 and #53. When you merge in the PR.

**Comment by leskerr** [comment]
@AESilky there's a missing triple quote at the end of a comment. Here's what it looks like when I pull the latest version of the branch:

```
    def set_officeID(self, officeId):
        """Sets the office/station ID for use on a connected wire

        self.officeID = officeId
```

I'll fix this, test the changes and add another commit to this pull request. (I hope I understand how this GitHub workflow works!)

**Comment by leskerr** [comment]
I added the missing triple quote and changed the code in `kobactions` to use the new `set_officeID` method instead of doing a direct assignment.

It seems to be working fine. Thanks for untangling the mess I created and for preserving the improvements you made (e.g. the `try` trap in `mkob.pyw` to catch keyboard interrupts).

**Comment by AESilky** [comment]
I will double check when I get home, but I don't believe you need to
specifically call the 'set_' method.

**Pull request merged**
