### PR TITLE
Es 166 lockups

### LINKED ISSUE #173: MKOB: Latest sender doesn't move to the bottom of the Senders List
When testing the branch to fix #166 that changed windows updates to be message based;
@leskerr noted: When I was sending, my line of the station list didn't get moved to the bottom of the list.

Proper operation is that:
1. The current sender is listed at the bottom of the list
2. Next up the list should be the previous sender
3. The list should continue to move up in the order a station last sent
4. Stations that are connected but haven't sent, should be listed next up the list

### PR DESCRIPTION
**Pull request by AESilky**
This intends to solve a number of issues.

Primarily #166. Also fixes #173 , #177 
It does seem to have introduced some problems with playback, but it would be nice to get realtime function working well and then adjust playback as needed.

### CODE REVIEW

**Review by leskerr — COMMENTED** [review]
I tried this version with two instances of MorseKOB 2.5 running at the same time (on the same computer) to simulate a three-way session. Generally it worked well, but I did notice these problems:

- When I send, my ID doesn't move to the bottom of the station list.
- When I'm connected to a wire and I click on the Connect button, the program disconnects from the wire but the the red 'connect' indicator stays red and I can't reconnect.

Just for fun, I added a second instance of MKOB 4.0 to the mix. I was using my bug and sounder with one of the MKOB 4's, and different choices of simulated sounders with the other three programs (sending with the keyboard, of course). It worked fine, other than the problems noted above.

KOB x 4

**Comment by AESilky** [comment]
For item 1, do you mean on the 4.0 you are sending from? Or on the other ones?
I will test with 4 instances on and off of a wire:
 - 2.5 and 4 on Win
 - 4 on Mac
 - 4 on Linux
and see what I get.

**Comment by leskerr** [comment]
What I meant was when I'm sending on MKOB 4, my ID doesn't drop to the bottom of my station list.

**Comment by AESilky** [comment]
Okay. Does it go to the bottom on the other MKOB 4 instance that is also connected?

**Comment by leskerr** [comment]
Yes, it goes to the bottom of the station list on the other MKOB 4 instance, the one that's listening. It stays at the top of the MKOB 4 instance that's sending.

**Comment by leskerr** [comment]
> * When I'm connected to a wire and I click on the Connect button, the program disconnects from the wire but the the red 'connect' indicator stays red and I can't reconnect.

Here's a clue. I used to have a one second delay in `kobmain.py` after disconnecting. I had it in there in an attempt to allow any pending incoming packets to be flushed, but that didn't seem to be successful. In my latest changes to get rid of unwanted delays, I commented out that delay. When I uncomment it, disconnecting works again. I still find the delay annoying, though.

```
        Internet.disconnect()
        Reader.flush()
        time.sleep(1.0)  # wait for any buffered code to complete
        connected = False  # just to make sure
```

**Comment by AESilky** [comment]
Thanks for the hint. I'll try to debug the disconnect and see if I can tell where it's getting hung up.

**Comment by AESilky** [comment]
I pushed a change that fixes the `connected` flag not being cleared on 'disconnect'. That got commented out along with the delay. 

I also changed the setting of the callbacks for the connected stations and the current sender to keep stations from showing up in the station list after it was cleared during disconnect. The 1 second delay was enough to keep this from happening, but without the delay stations would occasionally show up after the list was cleared. Now those callbacks are set on connect and cleared on disconnect.

**Review by leskerr — APPROVED** [review]
Well done! This is _much_ better than it ever was.

You can remove the commented out `time.sleep(1.0)` line if you like.

Just one minor problem remaining. If you disconnect from the wire while someone is sending, the local loop is left open. If the fix isn't straightforward, it can be left for another time. The workaround is to regain control of the local loop by toggling the Escape key.

**Comment by AESilky** [comment]
I'll remove the sleep line and look quickly at that. If it's not obvious
I'll nether this in and open an issue for it. Then I can work it and the
local sender not moving to the bottom of the list.

**Comment by AESilky** [comment]
@leskerr and I tested on Wire-11 today. Things worked well. Les noted a couple things, but I think it is fine to merge this now and then address the things he noticed.

**Pull request merged**
