### PR TITLE
Add ability for Feed.py to feed from a PyKOB recording (json) file.

### LINKED ISSUE #219: Feed.py: Add ability to use a PyKOB recorder file as a source
PyKOB added a recorder file in JSON format. The current `Feed.py` app can source an RSS file/feed. It would be useful for it to also accept a PyKOB recording (.json) file to use as the content to feed.

If a PyKOB recording file is specified, the content should be repeated with a short delay.

### PR DESCRIPTION
**Pull request by AESilky**
If path/url is a file and ends with '.json' process it as a PyKOB recording file. Otherwise process it as an RSS feed/file.

Closes #219

### CODE REVIEW

**Comment by AESilky** [comment]
I have this running on my server against my server. Wire 125 (for Instructograph Tape 5). It repeats.

**Comment by leskerr** [comment]
`Feed.py` fails for me when I specify a URL with a 'scheme' of `http:` or `file:`. For example:

```
C:\Users\Les\Documents\GitHub\PyKOB>py Feed.py 197 "Test feed, AC" "http://kob.sdf.org/morsekob/rss/beaufort.xml" 30
2021-01-06 07:33:18:    Starting Feed 1.9
Traceback (most recent call last):
  File "Feed.py", line 249, in <module>
    fileExists = filepath.exists()
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1329, in exists
    self.stat()
  File "C:\Users\Les\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1151, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'http:\\kob.sdf.org\\morsekob\\rss\\beaufort.xml'
```

It works if I just specify a path name for a local file.

A minor comment: the 'wpm' parameter has no meaning when playing a recorded JSON file, but it's required anyway. Maybe this should be optional, defaulting to something like 20wpm.

**Comment by AESilky** [comment]
That's interesting. I tested with an 'http://' URL and it worked. I just tested again and it's still working. I'll use your stack trace to try to fix it, but I may need your testing. Not sure why it's different. I'll try it on my Windows machine and my server and see if I get the problem.

Yes, I thought the same thing as I was coding it. I would like to have it use the newer argument processing so we can also include some of the options. Since the wpm is currently the last of the required arguments, I can easily make it optional and default to 20. If it were an earlier one I wouldn't touch it.

Also, I tried 'breaking in' to send by opening my key and the feed kept going. It did that for both this version and the feeds you are sending to my server. I didn't try it with a 2.5 client and I didn't try it against the main server.

**Comment by leskerr** [comment]
> I tried 'breaking in' to send by opening my key and the feed kept going. It did that for both this version and the feeds you are sending to my server. I didn't try it with a 2.5 client and I didn't try it against the main server.

Did you have the 'wait' parameter set to a nonzero value, to make the feed 'breakable'?

**Comment by AESilky** [comment]
Ah... I forgot to do that. I'll give it a try. I don't really think I need to make tape 5 'breakable', but I wanted to test my code - it should pause the recording and then resume it when you stop. If I have a feed with tape 1 or 2 it might make sense to have it be breakable.

**Comment by AESilky** [comment]
@leskerr , from PR #222 you mentioned issues with 'http://' and 'file://' URL's. For now, we won't support a 'http(s)://' reference to a recording file (should in the future), however, specifying a local file with a 'file://'URL should work.

I'm looking into that.

**Comment by AESilky** [comment]
The `recorder` code doesn't support a 'file://' URI as a path (maybe it should), so I changed the code to use `os.path.isfile`. That works correctly with Windows. A 'file://' URI is supported for an RSS file.

**Review by leskerr — APPROVED** [review]
That works. I'll try moving my feeds to the AC server on AWS tomorrow.

**Comment by AESilky** [comment]
I'll pull master and point my Instructograph feed a http://mtc-kob.dyndns.org/.

**Pull request merged**
